routes:
    home: 'Default:home'
    about: 'Default:about'
    contact: 'Default:contact'
    register: 'Security:register'
    login: 'Security:login'
    logout: 'Security:logout'
    upload: 'File:upload'
    delete: 'File:delete'
    rename: 'File:rename'
    replace: 'File:replace'
    download: 'File:download'
defaut_route: 'home'
db_config:
    name: 'filer'
    host: 'localhost'
    user: 'root'
    pass: ''
