routes:
    home: 'Default:home'
    about: 'Default:about'
    contact: 'Default:contact'
    register: 'Security:register'
    login: 'Security:login'
    logout: 'Security:logout'
    upload: 'File:upload'
    delete: 'File:delete'
    rename: 'File:rename'
    replace: 'File:replace'
    download: 'File:download'
    moveFile: 'File:moveFile'
    openEditFile: 'File:openEditFile'
    editFile: 'File:editFile'
    visualizeFile: 'File:visualizeFile'
    createNewFolder: 'Directory:createNewFolder'
    createDirectory: 'Directory:createDirectory'
    deleteDirectory: 'Directory:deleteDirectory'
    renameDirectory: 'Directory:renameDirectory'
    moveDirectory: 'Directory:moveDirectory'

defaut_route: 'home'
db_config:
    name: 'filer3'
    host: 'localhost'
    user: 'root'
    pass: ''
